In [1]:
from modules import api, stream
from datetime import datetime, timedelta

import numpy as np
import pandas as pd

In [2]:
api.initialize()  # checks tokens & loads variables
api.updateTokensAutomatic()  # starts thread to update tokens automatically

[INFO]: Access token last updated: 2024-05-22 12:51:52 (expires in 1532 seconds)
[INFO]: Refresh token last updated: 2024-05-22 12:22:09 (expires in 7 days)
[INFO]: Filling account number and account hash -> Done.
[INFO]: Initialization Complete
[INFO]: The access token has expired, updating automatically.
[INFO]: Access token updated: 2024-05-22 13:21:22.666390
[INFO]: The access token has expired, updating automatically.
[INFO]: Access token updated: 2024-05-22 13:51:23.900145

In [3]:
# Get hist0rical data
hist_spx = api.priceHistory.bySymbol("SPX", 
                                     periodType='month', 
                                     period=6, 
                                     frequencyType='daily', 
                                     frequency=1, 
                                     startDate=None,
                                     endDate=None, 
                                     needExtendedHoursData=False, 
                                     needPreviousClose=True).json()

In [41]:
spx_df = pd.DataFrame(hist_spx['candles'])
spx_df['datetime'] = pd.to_datetime(spx_df['datetime'],unit='ms')
spx_df.set_index('datetime')

                        open     high      low    close  volume
datetime
2023-11-21 06:00:00  4538.77  4542.14  4525.51  4538.19       0
2023-11-22 06:00:00  4553.04  4568.43  4545.05  4556.62       0
2023-11-24 06:00:00  4555.84  4560.31  4552.80  4559.34       0
2023-11-27 06:00:00  4554.86  4560.52  4546.32  4550.43       0
2023-11-28 06:00:00  4545.55  4568.14  4540.51  4554.89       0
...                      ...      ...      ...      ...     ...
2024-05-15 05:00:00  5263.26  5311.76  5263.26  5308.15       0
2024-05-16 05:00:00  5310.07  5325.49  5296.19  5297.10       0
2024-05-17 05:00:00  5303.10  5305.45  5283.59  5303.27       0
2024-05-20 05:00:00  5305.35  5325.32  5302.40  5308.13       0
2024-05-21 05:00:00  5298.69  5324.32  5297.87  5321.41       0

[125 rows x 5 columns]

In [52]:
# print(len(spx_df))

intraday_moves = np.zeros((len(spx_df),1))
# print(intraday_moves)

for ii,row in spx_df.iterrows():
    print(row['datetime'].)
    intraday_moves[ii] = row['close']/row['open']

21
22
24
27
28
29
30
1
4
5
6
7
8
11
12
13
14
15
18
19
20
21
22
26
27
28
29
2
3
4
5
8
9
10
11
12
16
17
18
19
22
23
24
25
26
29
30
31
1
2
5
6
7
8
9
12
13
14
15
16
20
21
22
23
26
27
28
29
1
4
5
6
7
8
11
12
13
14
15
18
19
20
21
22
25
26
27
28
1
2
3
4
5
8
9
10
11
12
15
16
17
18
19
22
23
24
25
26
29
30
1
2
3
6
7
8
9
10
13
14
15
16
17
20
21

[[0.99987221]
 [1.00078629]
 [1.00076824]
 [0.99902741]
 [1.00205476]
 [0.99534979]
 [1.00283872]
 [1.00772026]
 [1.00118527]
 [1.00217895]
 [0.99195636]
 [1.00366614]
 [1.00615576]
 [1.00632431]
 [1.00549986]
 [1.01310533]
 [0.99968439]
 [1.00105213]
 [1.00316998]
 [1.00519634]
 [0.98606847]
 [1.00475415]
 [1.00014935]
 [1.00333903]
 [1.00170317]
 [0.99935443]
 [0.99727152]
 [0.99950055]
 [0.99571223]
 [0.9981394 ]
 [1.001422  ]
 [1.0127219 ]
 [1.00307259]
 [1.00493914]
 [0.99751885]
 [0.99846593]
 [0.99866523]
 [1.00001688]
 [1.00437806]
 [1.00907578]
 [0.99938394]
 [1.001606  ]
 [0.99590677]
 [1.00153479]
 [1.00042136]
 [1.00714906]
 [0.99981323]
 [0.98907166]
 [1.0092736 ]
 [1.00865531]
 [0.99709916]
 [1.0008222 ]
 [1.00442586]
 [1.00055053]
 [1.00448426]
 [0.99900733]
 [0.99702694]
 [1.0048589 ]
 [1.00531466]
 [0.99491963]
 [0.99723209]
 [1.00378196]
 [1.00956571]
 [0.99762396]
 [0.99539171]
 [1.00070547]
 [1.00050521]
 [1.00214537]
 [1.00756496]
 [0.9999922 ]
 [0.99376384]
 [0.99935983]
 [1.00486714]
 [0.99210566]
 [1.00116981]
 [1.00797967]
 [0.99841886]
 [0.99523491]
 [0.99878594]
 [0.99896213]
 [1.00767062]
 [1.00828494]
 [0.99773481]
 [0.99841678]
 [0.99974519]
 [0.9951672 ]
 [1.00424391]
 [1.00120426]
 [0.99729934]
 [1.00029207]
 [1.00329588]
 [0.98153336]
 [1.0087983 ]
 [0.99827684]
 [0.99863524]
 [0.99859904]
 [1.00504741]
 [0.99069904]
 [0.98294065]
 [0.99739762]
 [0.99077525]
 [0.99594556]
 [0.99236631]
 [1.00466582]
 [1.00829215]
 [0.99739816]
 [1.00568539]
 [1.00301102]
 [1.00039889]
 [0.98665891]
 [0.99788428]
 [1.00294693]
 [1.00097798]
 [1.00745174]
 [1.00009639]
 [1.0036158 ]
 [1.00482749]
 [0.99946225]
 [0.99777187]
 [1.00489935]
 [1.00852893]
 [0.99755747]
 [1.00003206]
 [1.000524  ]
 [1.00428785]]